version: "3.8"

services:
  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
